name: CI Main

on: [push, pull_request]

jobs:
  CheckProjects:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v2
      - name: CheckProjects
        run: Scripts/check-projects.sh

  BuildMacOS:
    runs-on: macos-14
    needs: CheckProjects

    steps:
      - uses: actions/checkout@v4
      - name: Checkout Intro IRs
        uses: actions/checkout@v4
        with:
          repository: jd-13/body-and-soul-intro-irs
          token: ${{ secrets.IRS_SECRET }}
          path: IRs/Intro
      - name: Checkout Body IRs
        uses: actions/checkout@v4
        with:
          repository: jd-13/body-and-soul-body-irs
          token: ${{ secrets.IRS_SECRET }}
          path: IRs/Body
      - name: Checkout Soul IRs
        uses: actions/checkout@v4
        with:
          repository: jd-13/body-and-soul-soul-irs
          token: ${{ secrets.IRS_SECRET }}
          path: IRs/Soul
      - name: Checkout FX IRs
        uses: actions/checkout@v4
        with:
          repository: jd-13/body-and-soul-fx-irs
          token: ${{ secrets.IRS_SECRET }}
          path: IRs/FX
      - name: RunBuild
        run: Scripts/macos/build.sh
      - uses: actions/upload-artifact@v4
        if: ${{ success() }}
        with:
          name: BodyandSoul-macOS
          path: Scripts/macos/dist

  BuildWindows:
    runs-on: windows-2019
    needs: CheckProjects

    steps:
      - uses: actions/checkout@v4
      - name: Checkout Intro IRs
        uses: actions/checkout@v4
        with:
          repository: jd-13/body-and-soul-intro-irs
          token: ${{ secrets.IRS_SECRET }}
          path: IRs/Intro
      - name: Checkout Body IRs
        uses: actions/checkout@v4
        with:
          repository: jd-13/body-and-soul-body-irs
          token: ${{ secrets.IRS_SECRET }}
          path: IRs/Body
      - name: Checkout Soul IRs
        uses: actions/checkout@v4
        with:
          repository: jd-13/body-and-soul-soul-irs
          token: ${{ secrets.IRS_SECRET }}
          path: IRs/Soul
      - name: Checkout FX IRs
        uses: actions/checkout@v4
        with:
          repository: jd-13/body-and-soul-fx-irs
          token: ${{ secrets.IRS_SECRET }}
          path: IRs/FX
      - name: SetupMSBuild
        uses: microsoft/setup-msbuild@v1.0.2
      - name: RunBuild
        shell: cmd
        run: Scripts\windows\build.bat
      - uses: actions/upload-artifact@v4
        if: ${{ success() }}
        with:
          name: BodyandSoul-windows
          path: dist
