name: CI Main

on: [push, pull_request]

jobs:
  BuildMacOS:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v2
      - name: Checkout IRs
        uses: actions/checkout@v4
        with:
          repository: jd-13/body-and-soul-intro-irs
          token: ${{ secrets.INTRO_IRS_SECRET }}
          path: IRs
      - name: RunBuild
        run: Scripts/macos/build.sh
      - uses: actions/upload-artifact@v2
        if: ${{ success() }}
        with:
          name: BodyandSoulIntro-macOS
          path: Scripts/macos/dist

  BuildWindows:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      - name: Checkout IRs
        uses: actions/checkout@v4
        with:
          repository: jd-13/body-and-soul-intro-irs
          token: ${{ secrets.INTRO_IRS_SECRET }}
          path: IRs
      - name: SetupMSBuild
        uses: microsoft/setup-msbuild@v1.0.2
      - name: RunBuild
        shell: cmd
        run: Scripts\windows\build.bat
      - uses: actions/upload-artifact@v2
        if: ${{ success() }}
        with:
          name: BodyandSoulIntro-windows
          path: Release
